import Link from"next/link";
import{redirect}from"next/navigation";
import{revalidatePath}from"next/cache";
import{randomUUID}from"node:crypto";
import{requireAdmin}from"@/lib/auth";
import{ensureSchema,getSettings,requireDb}from"@/lib/db";
import LogoutButton from"@/components/LogoutButton";
export const dynamic="force-dynamic";

const text=(v:FormDataEntryValue|null,max=5000)=>String(v??"").trim().slice(0,max);
async function adminGuard(){"use server";const admin=await requireAdmin();if(!admin)redirect("/login");return admin;}
async function saveSettings(data:FormData){"use server";await adminGuard();await ensureSchema();const db=requireDb();for(const key of["description","mission","vision","address","phone","general_whatsapp"]){const value=text(data.get(key));if(value)await db`INSERT INTO settings(key,value,updated_at)VALUES(${key},${value},NOW()) ON CONFLICT(key)DO UPDATE SET value=EXCLUDED.value,updated_at=NOW()`;}revalidatePath("/admin");revalidatePath("/");}
async function addGroup(data:FormData){"use server";await adminGuard();await ensureSchema();const name=text(data.get("name"),120),url=text(data.get("invite_url"),500),audience=text(data.get("audience"),120)||"general";if(name&&url.startsWith("https://chat.whatsapp.com/"))await requireDb()`INSERT INTO whatsapp_groups(id,name,invite_url,audience)VALUES(${randomUUID()},${name},${url},${audience})`;revalidatePath("/admin");revalidatePath("/portal");}
async function addUnit(data:FormData){"use server";await adminGuard();await ensureSchema();const name=text(data.get("name"),120),type=text(data.get("type"),30),parent=text(data.get("parent_id"),60);if(name&&["state","lga","lcda","ward"].includes(type))await requireDb()`INSERT INTO organization_units(id,name,type,parent_id)VALUES(${randomUUID()},${name},${type},${parent||null}) ON CONFLICT DO NOTHING`;revalidatePath("/admin");}
async function addPosition(data:FormData){"use server";await adminGuard();await ensureSchema();const title=text(data.get("title"),120),department=text(data.get("department"),120),level=text(data.get("level"),50)||"national",deputy=text(data.get("deputy_title"),120);if(title)await requireDb()`INSERT INTO leadership_positions(id,title,department,level,deputy_title)VALUES(${randomUUID()},${title},${department||null},${level},${deputy||null})`;revalidatePath("/admin");}
async function updateMember(data:FormData){"use server";const admin=await adminGuard();await ensureSchema();const id=text(data.get("id"),60),role=text(data.get("role"),30),status=text(data.get("status"),30);if(id===String(admin.id)&&(role!==String(admin.role)||status!=="active"))return;const permitted=String(admin.role)==="super_admin"?["member","coordinator","executive","admin","super_admin"]:["member","coordinator","executive"];if(permitted.includes(role)&&["active","suspended"].includes(status))await requireDb()`UPDATE members SET role=${role},status=${status},updated_at=NOW()WHERE id=${id} AND (role!='super_admin' OR ${String(admin.role)}='super_admin')`;revalidatePath("/admin");}

export default async function Admin(){const admin=await requireAdmin();if(!admin)redirect("/login");await ensureSchema();const db=requireDb();const[settings,members,units,groups,positions,stats]=await Promise.all([getSettings(),db`SELECT id,membership_number,first_name,last_name,phone,email,category,lga,ward,role,status,created_at FROM members ORDER BY created_at DESC LIMIT 100`,db`SELECT u.id,u.name,u.type,p.name parent_name FROM organization_units u LEFT JOIN organization_units p ON p.id=u.parent_id ORDER BY u.type,u.name`,db`SELECT id,name,invite_url,audience,active FROM whatsapp_groups ORDER BY name`,db`SELECT id,title,department,level,deputy_title,active FROM leadership_positions ORDER BY level,title`,db`SELECT COUNT(*)::int total,COUNT(*)FILTER(WHERE role IN('admin','super_admin'))::int admins,COUNT(*)FILTER(WHERE created_at>NOW()-INTERVAL '30 days')::int new_members FROM members`]);const s=stats[0];return <main className="portal"><aside className="sidebar"><Link href="/" className="brand"><img src="/cep-logo.jpeg" alt="CEP"/><b>CEP <small>ADMIN</small></b></Link><nav className="side-nav"><a href="#dashboard" className="active">Dashboard</a><a href="#members">Members</a><a href="#structure">Structure</a><a href="#leadership">Leadership</a><a href="#groups">WhatsApp groups</a><a href="#content">Website content</a></nav></aside><section className="workspace"><div className="workspace-head"><div><p className="eyebrow">SECURE ADMINISTRATION</p><h1>CEP control centre</h1><p>Signed in as {String(admin.first_name)} {String(admin.last_name)}</p></div><LogoutButton/></div><div className="stat-grid" id="dashboard">{[["Total members",String(s.total)],["New this month",String(s.new_members)],["Administrators",String(s.admins)],["Structure units",String(units.length)]].map(x=><article className="stat" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong></article>)}</div>
<article className="panel wide" id="members"><div className="panel-title"><h2>Members</h2><a className="button small" href="/api/admin/members/export">Download CSV</a></div><div className="table-scroll"><table><thead><tr><th>Member</th><th>Category</th><th>Location</th><th>Role & status</th></tr></thead><tbody>{members.map((m:any)=><tr key={String(m.id)}><td><strong>{String(m.first_name)} {String(m.last_name)}</strong><br/><small>{String(m.membership_number)} · {String(m.phone)}</small></td><td>{String(m.category)}</td><td>{String(m.lga)}<br/><small>{String(m.ward)}</small></td><td><form action={updateMember} className="inline-form"><input type="hidden" name="id" value={String(m.id)}/><select name="role" defaultValue={String(m.role)} disabled={String(m.role)==="super_admin"&&String(admin.role)!=="super_admin"}>{(String(admin.role)==="super_admin"?["member","coordinator","executive","admin","super_admin"]:["member","coordinator","executive"]).map(x=><option key={x}>{x}</option>)}</select><select name="status" defaultValue={String(m.status)} disabled={String(m.role)==="super_admin"&&String(admin.role)!=="super_admin"}><option>active</option><option>suspended</option></select><button disabled={String(m.role)==="super_admin"&&String(admin.role)!=="super_admin"}>Save</button></form></td></tr>)}</tbody></table></div></article>
<div className="panel-grid"><article className="panel" id="structure"><h2>Lagos structure</h2><form action={addUnit} className="stack-form"><input name="name" placeholder="Unit name" required/><select name="type"><option>state</option><option>lga</option><option>lcda</option><option>ward</option></select><select name="parent_id" defaultValue=""><option value="">No parent</option>{units.map((u:any)=><option key={String(u.id)} value={String(u.id)}>{String(u.type)} · {String(u.name)}</option>)}</select><button className="button small">Add unit</button></form><div className="quick-list compact">{units.slice(0,30).map((u:any)=><div className="quick-item" key={String(u.id)}><span>{String(u.name)}</span><span className="tag">{String(u.type)}</span></div>)}</div></article>
<article className="panel" id="leadership"><h2>Leadership & departments</h2><form action={addPosition} className="stack-form"><input name="title" placeholder="Position title" required/><input name="department" placeholder="Department"/><input name="deputy_title" placeholder="Deputy or assistant title"/><select name="level"><option>national</option><option>state</option><option>lga</option><option>lcda</option><option>ward</option></select><button className="button small">Add position</button></form>{positions.map((p:any)=><div className="quick-item" key={String(p.id)}><span>{String(p.title)}<small>{p.department?` · ${String(p.department)}`:""}</small></span><span className="tag">{String(p.level)}</span></div>)}</article></div>
<div className="panel-grid"><article className="panel" id="groups"><h2>WhatsApp groups</h2><form action={addGroup} className="stack-form"><input name="name" placeholder="Group name" required/><input name="invite_url" type="url" placeholder="https://chat.whatsapp.com/..." required/><input name="audience" placeholder="general, LGA or ward"/><button className="button small">Add group</button></form>{groups.map((g:any)=><div className="quick-item" key={String(g.id)}><a href={String(g.invite_url)} target="_blank" rel="noreferrer">{String(g.name)}</a><span className="tag">{String(g.audience)}</span></div>)}</article>
<article className="panel" id="content"><h2>Editable website content</h2><form action={saveSettings} className="stack-form"><label>Description<textarea name="description" defaultValue={settings.description}/></label><label>Mission<textarea name="mission" defaultValue={settings.mission}/></label><label>Vision<textarea name="vision" defaultValue={settings.vision}/></label><label>Address<input name="address" defaultValue={settings.address}/></label><label>Phone<input name="phone" defaultValue={settings.phone}/></label><label>General WhatsApp<input name="general_whatsapp" defaultValue={settings.general_whatsapp}/></label><button className="button small">Save website content</button></form></article></div></section></main>}
