import Link from "next/link";import{ArrowRight,BriefcaseBusiness,Handshake,Network,TrendingUp,MapPin,Phone}from"lucide-react";
const benefits=[[TrendingUp,"Growth & Funding","Discover pathways, insights and connections that move ventures forward."],[Handshake,"Strategic Access","Build partnerships with people who understand your ambition."],[Network,"High-Value Networks","Connect across professions, industries and communities in Lagos."],[BriefcaseBusiness,"Business Intelligence","Access opportunities, knowledge and professional support."]]as const;
export default function Home(){return <main><header className="nav"><Link href="/" className="brand"><img src="/cep-logo.jpeg" alt="CEP logo"/><b>CEP <small>NIGERIA</small></b></Link><nav><a href="#about">About</a><a href="#benefits">Benefits</a><a href="#contact">Contact</a></nav><div className="actions"><Link href="/login">Member login</Link><Link href="/register" className="button small">Join CEP</Link></div></header>
<section className="hero"><div><p className="eyebrow">COALITION OF ENTREPRENEURS & PROFESSIONALS</p><h1>Build boldly.<br/><em>Grow together.</em></h1><p className="lead">A community for ambitious entrepreneurs and professionals ready to scale their ventures, access opportunities and build valuable strategic relationships.</p><div className="actions hero-actions"><Link href="/register" className="button">Become a member <ArrowRight size={18}/></Link><a className="button outline" href="https://chat.whatsapp.com/KO2hT8zs0nA3WJqFVeSec3?s=cl&p=i&mlu=0&ilr=0">Join our WhatsApp</a></div><div className="trust"><span>Starting in Lagos</span><span>Built for professionals</span><span>Connected for growth</span></div></div><div className="hero-logo"><i></i><img src="/cep-logo.jpeg" alt="CEP emblem"/><aside><strong>One coalition.</strong><span>Many possibilities.</span></aside></div></section>
<section id="about" className="statement"><p className="eyebrow gold">OUR PURPOSE</p><h2>Don’t build alone.</h2><p>CEP brings entrepreneurs, professionals and emerging leaders into one trusted community where ideas, opportunities and the right connections accelerate meaningful growth.</p></section>
<section id="benefits" className="benefits"><header><div><p className="eyebrow">WHY CEP</p><h2>More than membership.<br/>A platform for progress.</h2></div></header><div className="benefit-grid">{benefits.map(([Icon,t,d],i)=><article key={t}><span>0{i+1}</span><Icon/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="mission"><article><p className="eyebrow">MISSION</p><h2>To connect, equip and promote entrepreneurs and professionals through strategic relationships, shared intelligence and access to opportunities that strengthen enterprise, careers and communities.</h2></article><article><p className="eyebrow gold">VISION</p><h2>To become Nigeria’s most trusted coalition for enterprise growth, professional advancement and collaborative impact.</h2></article></section>
<section className="cta"><div><p className="eyebrow gold">READY TO SCALE YOUR VENTURE?</p><h2>Your next opportunity may begin with the right connection.</h2></div><Link href="/register" className="button gold-button">Join the coalition <ArrowRight size={18}/></Link></section>
<footer id="contact"><Link href="/" className="brand"><img src="/cep-logo.jpeg" alt="CEP"/><b>CEP <small>NIGERIA</small></b></Link><div><h4>Visit us</h4><p><MapPin size={16}/>3 Awolowo Way, Ikeja, Lagos</p></div><div><h4>Call us</h4><p><Phone size={16}/><a href="tel:+2348148328738">+234 814 832 8738</a></p></div><p>© 2026 CEP Nigeria</p></footer></main>}
